### PR TITLE
2020: Emergency Update

### PR DESCRIPTION
**Pull request by sadn1ck**
Following changes are required:

- [x] Move the 2020 batch to the alumni portion.
- [x] Update cards for the current GS and Treasurer. GS - Suryansh Gupta, Treasurer - Arijit Saha
- [x] Update professor in charge. Prof. Shyamalendu Kandar, IT
- [x] Update rest of the club members with 2021 and 2022 batch.

### CODE REVIEW

**Review by raydwaipayan — APPROVED** [review]
LGTM! Great Job!

**Comment by raydwaipayan** [comment]
Fixes #10

**Comment by indrarahul** [comment]
@raydwaipayan Should I merge it ?

**Comment by raydwaipayan** [comment]
> @raydwaipayan Should I merge it ?

Yes please, it seems good!

Fixes #10

**Pull request merged**
