### PR TITLE
New website by Rahul Indra

### PR DESCRIPTION
**Pull request by soubh1k**
New website by Rahul Indra. Please provide feedback.

### CODE REVIEW

**Review by prateekiiest — APPROVED** [review]

**Comment by soubh1k** [comment]
It is not yet merged. The previous website is still showing.

**Comment by prateekiiest** [comment]
Can you provide a preview link or deployment link?
@indrarahul2013 
@soubh1k

**Comment by soubh1k** [comment]
Then this website needs to be hosted someplace else. Just merge the changes. If it is not as required then we can revert back.

**Comment by prateekiiest** [comment]
ok

**Comment by soubh1k** [comment]
Alright. This looks good.

**Pull request merged**
